sudo: false

language: python

cache:
  directories:
  - $HOME/.pip-cache/

matrix:
  include:
    - python: "3.5"
      env: BUILD=conda DEPLOY=yes
      os: linux
    - python: "2.7"
      env: BUILD=conda DEPLOY=no
      os: linux

install:
- if [[ "$BUILD" == "conda" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    bash miniconda.sh -b -f -p $HOME/miniconda;
    export PATH="$HOME/miniconda/bin:$PATH";
    hash -r;
    conda config --set always_yes yes --set changeps1 no;
    conda update -q conda;
    conda install -n root _license;
    conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION;
    source activate testenv;
  fi
  
- export REQUIREMENTS=`cat requirements.txt | tr '\n' ' '`
- echo $REQUIREMENTS;

- if [[ "$BUILD" == "conda" ]]; then
    export REQUIREMENTS=`echo $REQUIREMENTS | sed 's/pyhmsa//g'`;
    conda install $REQUIREMENTS;
    pip install pyhmsa codecov;
  elif [[ "$BUILD" == "pip" ]]; then
    pip install --cache-dir $HOME/.pip-cache --upgrade pip codecov $REQUIREMENTS;
  fi
  
- python setup.py develop

script:
- nosetests

after_success:
- codecov

notifications:
  email: false

deploy:
  - provider: pypi
    user: philippe.pinard
    password:
      secure: nC/0Lj2H/5BZo4BAhc29fYa6AJZL+UBVfFBcoX57XMA3AD+iCHWH0HJJXoiGvKtP3M/NB1tXAB+5Tj0R6q0bUOiMnf1fulckAVHlPI7r9CfukS62/peWcJYxpsFCOhyiqkTbNnwsX2JdRdrO0U/tUztqWUlazK43ziQCDBdqPp4=
    distributions: sdist
    on:
      tags: true
      repo: pyhmsa/pyhmsa-matlab
      condition: "$DEPLOY = yes"
